name: Test GitHub Meta


on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]


permissions:
  contents: read
  pull-requests: read


jobs:
  commit-meta:
    name: Validate Commit Conventions
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commit Validation
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,docs,test,ci,refactor,perf,chore,revert"


  pr-meta:
    name: Validate PR Conventions
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Pull Request Validation
        uses: amannn/action-semantic-pull-request@v5
        with:
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  codecov-file:
    name: Validate CodeCov File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1


      - name: "'codecov.yml' Validation"
        run: |
          if [[ -f "./codecov.yml" ]]; then
            curl -f -X POST --data-binary @codecov.yml https://codecov.io/validate \
            || { echo "The 'codecov.yml' file validation was not successful."; exit 1; }
          fi
